name: manual_camera
description: A Flutter plugin for manually controlling the camera on Android devices. All the native functions of the Flutter official Camera plugin are available.
version: 0.0.3

homepage: https://afonsoraposo.com
repository: https://github.com/afonsocraposo/manual_camera

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider:
  video_player:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic:

flutter:
  plugin:
    platforms:
      android:
        package: com.afonsoraposo.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin

environment:
  sdk: ">=3.2.4 <4.0.0"
